train:
  epochs: 100
  batch_size: 256
  lr: 5.0e-4 #5e-4
  itr_per_epoch: 1.0e+8
  regularization: 0.0

diffusion:
  layers: 2 # 6
  channels: 32 #192
  nheads: 8
  diffusion_embedding_dim: 128
  beta_start: 0.01
  beta_end: 0.5
  num_steps: 400
  schedule: cosine
  is_linear: True

model:
  is_unconditional: 0
  timeemb: 128
  featureemb: 8
  target_strategy: "test"
